apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-eventsource
  namespace: argo-events
spec:
  github:
    app-push:
      owner: "devopswithchaitanya"
      repository: "myapp"
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
      events:
        - push
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json
